import { StyleSheet } from "react-native";
const goalsStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 100,
  },
  backButton: {
    alignSelf: "flex-start",
    marginBottom: 15,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#312d69",
    borderRadius: 8,
  },
  backButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: "white",
    marginBottom: 5,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    color: "#ddd",
    marginBottom: 20,
    textAlign: "center",
  },
  card: {
    backgroundColor: "#0b1324",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#1e293b",
    shadowOpacity: 0,
    elevation: 0,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 10,
    color: "#e2e8f0",
  },
  cardText: {
    fontSize: 15,
    marginBottom: 10,
    color: "#94a3b8",
  },
  input: {
    borderWidth: 1,
    borderColor: "#1e293b",
    backgroundColor: "#0b1324",
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 10,
    color: "#e2e8f0",
    fontSize: 16,
  },
  button: {
    backgroundColor: "#f59e0b",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 15,
  },
  progressBar: {
    height: 8,
    backgroundColor: "#e2e8f015",
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 10,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#22c55e",
  },
  progressText: {
    fontSize: 14,
    marginTop: 5,
    color: "#94a3b8",
  },
  aportContainer: {
    flexDirection: "row",
    marginTop: 10,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  aportButton: {
    backgroundColor: "#1e293b",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  aportButtonText: {
    color: "#e2e8f0",
    fontWeight: "600",
    fontSize: 14,
  },
  customAportButton: {
    backgroundColor: "#f59e0b",
    padding: 8,
    borderRadius: 999,
    justifyContent: "center",
    alignItems: "center",
    minWidth: 40,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  cardActions: {
    flexDirection: "row",
    gap: 8,
  },
  actionButton: {
    padding: 6,
    borderRadius: 999,
    backgroundColor: "#1e293b",
  },
  editButton: {
    backgroundColor: "#3b82f6",
  },
  deleteButton: {
    backgroundColor: "#f43f5e",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#0b1324",
    borderRadius: 20,
    padding: 25,
    width: "100%",
    maxWidth: 420,
    borderWidth: 1,
    borderColor: "#1e293b",
    shadowOpacity: 0,
    elevation: 0,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#e2e8f0",
    marginBottom: 20,
    textAlign: "center",
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#cbd5e1",
    marginBottom: 8,
    marginTop: 5,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
  },
  cancelButton: {
    backgroundColor: "#f43f5e",
  },
  saveButton: {
    backgroundColor: "#22c55e",
  },
  modalButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 15,
  },
});

export default goalsStyles;
